# Generated by Django 3.2 on 2021-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='title',
        ),
        migrations.AddField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
