# Generated by Django 3.2 on 2021-05-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_gym_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='aadhar',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
