# Generated by Django 3.2 on 2021-05-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_gym_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='aadhar',
            field=models.ImageField(default='images/image.jpeg', upload_to='images'),
        ),
    ]
